<h1>
Q2_part1-6:

In [ ]:
import gdown

file_id = "1-AlW7oNJHaqi3xk_9dWHUS52Dzl_FmFW"

gdown.download(
    f"https://drive.google.com/uc?id={file_id}",
    "train.csv",
    quiet=False)

Downloading...
From (original): https://drive.google.com/uc?id=1-AlW7oNJHaqi3xk_9dWHUS52Dzl_FmFW
From (redirected): https://drive.google.com/uc?id=1-AlW7oNJHaqi3xk_9dWHUS52Dzl_FmFW&confirm=t&uuid=87478477-6eb7-46bc-bbaf-481dfca62584
To: /content/train.csv
100%|██████████| 635M/635M [00:08<00:00, 77.3MB/s]

'train.csv'

In [ ]:
import pandas as pd

# خواندن دیتاست
df = pd.read_csv("train.csv")

# نمایش چند سطر اول
df.head()

/tmp/ipykernel_1581/3842993039.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("train.csv")

,overall,vote,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime
0,2,NaN,False,2016-11-11,A2OSUEZJIN7BI,0511189877,NaN,Chris,I have an older URC-WR7 remote and thought thi...,Cannot Learn,1478822400
1,5,NaN,True,2016-06-06,A2NETQRG6JHIG7,0511189877,NaN,Qrysta White,First time I've EVER had a remote that needed ...,zero programming needed! Miracle!?,1465171200
2,4,NaN,True,2016-03-10,A12JHGROAX49G7,0511189877,NaN,Linwood,Got them and only 2 of them worked. company ca...,Works Good and programs easy.,1457568000
3,5,NaN,True,2016-01-14,A1KV65E2TMMG6F,0511189877,NaN,Dane Williams,I got tired of the remote being on the wrong s...,Same as TWC remote,1452729600
4,5,NaN,True,2016-10-20,A280POPEWI0NSA,0594459451,NaN,Kristina H.,After purchasing cheap cords from another webs...,Good Quality Cord,1476921600

In [ ]:
import gdown

file_id = "1I9aPAvvYgQWdHGKtnd7IeTGXpx8vOm4h"

gdown.download(
    f"https://drive.google.com/uc?id={file_id}",
    "product_mapping.csv",
    quiet=False
)

Downloading...
From: https://drive.google.com/uc?id=1I9aPAvvYgQWdHGKtnd7IeTGXpx8vOm4h
To: /content/product_mapping.csv
100%|██████████| 97.3M/97.3M [00:00<00:00, 208MB/s]

'product_mapping.csv'

In [ ]:
# خواندن جدول نگاشت شناسه‌ی محصولات به عنوان و برند آن‌ها
product_map = pd.read_csv("product_mapping.csv")

# نمایش چند سطر اول
product_map.head()

,asin,title,brand
0,0011300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,GeoVision
1,0043396828,"Books ""Handbook of Astronomical Image Processi...",33 Books Co.
2,0060009810,One Hot Summer,Visit Amazon's Carolina Garcia Aguilera Page
3,0060219602,Hurray for Hattie Rabbit: Story and pictures (...,Visit Amazon's Dick Gackenbach Page
4,0060786817,sex.lies.murder.fame.: A Novel,Visit Amazon's Lolita Files Page

In [ ]:
# بررسی نام ستون‌های قدیم
df.columns

Index(['overall', 'vote', 'verified', 'reviewTime', 'reviewerID', 'asin',
       'style', 'reviewerName', 'reviewText', 'summary', 'unixReviewTime',
       'title_x', 'brand_x', 'title_y', 'brand_y'],
      dtype='object')

In [ ]:
# اتصال برند به دیتاست اصلی بر اساس Asin
df = df.merge(product_map, on="asin", how="left")

# بررسی نام ستون‌های جدید
df.columns

Index(['overall', 'vote', 'verified', 'reviewTime', 'reviewerID', 'asin',
       'style', 'reviewerName', 'reviewText', 'summary', 'unixReviewTime',
       'title_x', 'brand_x', 'title_y', 'brand_y', 'title', 'brand'],
      dtype='object')

In [ ]:
# پیدا کردن 10 برند با بیشترین تعداد نظر
top10_brands = (df["brand"].value_counts().head(10).index)

# محاسبه تعداد نظرات و میانگین امتیاز برای این برندها
brand_analysis = (df[df["brand"].isin(top10_brands)].groupby("brand")
    .agg(review_count=("overall", "count"), average_rating=("overall", "mean"))
    .reset_index())

# مرتب‌سازی بر اساس میانگین امتیاز
brand_analysis = brand_analysis.sort_values(by="average_rating", ascending=False)

# تصحیح ایندکس‌ها
brand_analysis = brand_analysis.reset_index(drop=True)

# شروع ایندکس‌ها از یک به‌جای صفر
brand_analysis.index = brand_analysis.index + 1

# نمایش جدول نهایی
brand_analysis

           brand  review_count  average_rating
1          Canon          8807        4.455093
2          Anker          9860        4.244320
3   AmazonBasics         13213        4.201468
4       StarTech         10984        4.162418
5           Sony         16540        4.014148
6       Logitech         17504        3.964122
7        NETGEAR          9641        3.945649
8        Samsung         15427        3.942114
9        TP-LINK          9773        3.928681
10          Asus         11928        3.855550