In [1]:
! gdown 1-AlW7oNJHaqi3xk_9dWHUS52Dzl_FmFW
! gdown 1-8TsrqTRFP-q9TM-6HinhO0ZVXFHq9TB
! gdown 1I9aPAvvYgQWdHGKtnd7IeTGXpx8vOm4h

Downloading...
From (original): https://drive.google.com/uc?id=1-AlW7oNJHaqi3xk_9dWHUS52Dzl_FmFW
From (redirected): https://drive.google.com/uc?id=1-AlW7oNJHaqi3xk_9dWHUS52Dzl_FmFW&confirm=t&uuid=d3f1a74c-3005-40b6-ab3a-74b664a5e083
To: /content/train_data.csv
100% 635M/635M [00:08<00:00, 76.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1-8TsrqTRFP-q9TM-6HinhO0ZVXFHq9TB
To: /content/test_data.csv
100% 15.6M/15.6M [00:00<00:00, 101MB/s]
Downloading...
From: https://drive.google.com/uc?id=1I9aPAvvYgQWdHGKtnd7IeTGXpx8vOm4h
To: /content/title_brand.csv
100% 97.3M/97.3M [00:00<00:00, 166MB/s]

In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
train_df = pd.read_csv("train_data.csv")
test_df = pd.read_csv("test_data.csv")
product_df = pd.read_csv("title_brand.csv")

/tmp/ipykernel_884/2058225489.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  train_df = pd.read_csv("train_data.csv")

In [4]:
print("Train:", train_df.shape)
print("Test :", test_df.shape)
print("Products:", product_df.shape)

train_df.head()

Train: (838944, 11)
Test : (20000, 10)
Products: (786445, 3)

,overall,vote,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime
0,2,NaN,False,2016-11-11,A2OSUEZJIN7BI,0511189877,NaN,Chris,I have an older URC-WR7 remote and thought thi...,Cannot Learn,1478822400
1,5,NaN,True,2016-06-06,A2NETQRG6JHIG7,0511189877,NaN,Qrysta White,First time I've EVER had a remote that needed ...,zero programming needed! Miracle!?,1465171200
2,4,NaN,True,2016-03-10,A12JHGROAX49G7,0511189877,NaN,Linwood,Got them and only 2 of them worked. company ca...,Works Good and programs easy.,1457568000
3,5,NaN,True,2016-01-14,A1KV65E2TMMG6F,0511189877,NaN,Dane Williams,I got tired of the remote being on the wrong s...,Same as TWC remote,1452729600
4,5,NaN,True,2016-10-20,A280POPEWI0NSA,0594459451,NaN,Kristina H.,After purchasing cheap cords from another webs...,Good Quality Cord,1476921600

<div dir="rtl">
    <h2>سوال 3</h2>
    <div>
    از بین نظردهندگان، ۱۰ نفری که در مجموع نظرات‌شان بیشتر مفید واقع شده (مجموع vote بیشتری داشته‌اند) را پیدا کنید. به‌عنوان مثال اگر شخص «الف» مجموعاً ۲۰ نظر ثبت کرده باشد، باید مجموع مقدار vote تمام ۲۰ نظر وی را محاسبه کنید. این کار را برای تمام افراد انجام داده و ۱۰ نفر برتر را پیدا کنید. نام هر فرد و مجموع vote آن را به‌ترتیب نمایش دهید.
    </div>
</div>

In [5]:
train_df['vote'].dtype

dtype('O')

In [6]:
train_df['vote'].isna().sum()

np.int64(647476)

In [7]:
train_df['vote'] = pd.to_numeric(train_df['vote'], errors='coerce').fillna(0)

In [11]:
top_clients = train_df.groupby(["reviewerID", "reviewerName"])["vote"].sum().reset_index(name="total_vote")
top_clients

                  reviewerID       reviewerName  total_vote
0       A00101847G3FJTWYGNQA         Cang Cheng         3.0
1       A0014476IZYE2N3XTK4K               Luis         0.0
2       A00408825PVJW7GFLEGU             SGnemo         0.0
3       A0102335OJZYGD6JG8YQ  Modern-Freakazoid         0.0
4       A0103849GBVWICKXD4T6            TB96762         9.0
...                      ...                ...         ...
324322         AZZX3COL525E6      John Conkeroo         0.0
324323         AZZY4W8E5AX2K              Sofia         0.0
324324         AZZYW4YOE1B6E            tmybrgr        11.0
324325         AZZZF5PSCPILV           Elle Bee         0.0
324326         AZZZU3P1UQZ0C       maedchen0324         0.0

[324327 rows x 3 columns]

In [12]:
top_10 = top_clients.sort_values("total_vote", ascending=False).head(10).reset_index(drop=True)
top_10.index += 1

top_10

        reviewerID       reviewerName  total_vote
1   A25GROL6KJV3QG       Benson Leung      4572.0
2   A2IK776FY6MEMG            Obi Wan      1608.0
3   A1A39899KH5QCI       Chris Winter      1352.0
4    AMYCUX8EWEUVV           Mayra S.      1342.0
5    A9K7V1MKJ9BOJ         VermontGuy      1337.0
6   A1UQUDT2Q0YENM            Michael      1230.0
7   A3R1WFO4KIUQXZ      PhotoGraphics      1209.0
8   A2Z9APP5B09MFY           Nicholas      1188.0
9    AOEAD7DPLZE53  NLee the Engineer      1103.0
10   AZPCDY9OQ605E            David H      1045.0

In [14]:
res = top_10[["reviewerName", "total_vote"]]
res

         reviewerName  total_vote
1        Benson Leung      4572.0
2             Obi Wan      1608.0
3        Chris Winter      1352.0
4            Mayra S.      1342.0
5          VermontGuy      1337.0
6             Michael      1230.0
7       PhotoGraphics      1209.0
8            Nicholas      1188.0
9   NLee the Engineer      1103.0
10            David H      1045.0