In [1]:
! gdown 1-AlW7oNJHaqi3xk_9dWHUS52Dzl_FmFW
! gdown 1-8TsrqTRFP-q9TM-6HinhO0ZVXFHq9TB
! gdown 1I9aPAvvYgQWdHGKtnd7IeTGXpx8vOm4h

Downloading...
From (original): https://drive.google.com/uc?id=1-AlW7oNJHaqi3xk_9dWHUS52Dzl_FmFW
From (redirected): https://drive.google.com/uc?id=1-AlW7oNJHaqi3xk_9dWHUS52Dzl_FmFW&confirm=t&uuid=e0644587-6406-44c4-91c7-95039783e0e9
To: /content/train_data.csv
100% 635M/635M [00:16<00:00, 38.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1-8TsrqTRFP-q9TM-6HinhO0ZVXFHq9TB
To: /content/test_data.csv
100% 15.6M/15.6M [00:00<00:00, 99.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1I9aPAvvYgQWdHGKtnd7IeTGXpx8vOm4h
To: /content/title_brand.csv
100% 97.3M/97.3M [00:01<00:00, 85.4MB/s]

In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
train_df = pd.read_csv("train_data.csv")
test_df = pd.read_csv("test_data.csv")
product_df = pd.read_csv("title_brand.csv")

/tmp/ipykernel_2921/2058225489.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  train_df = pd.read_csv("train_data.csv")

In [ ]:
print("Train:", train_df.shape)
print("Test :", test_df.shape)
print("Products:", product_df.shape)

train_df.head()

Train: (838944, 11)
Test : (20000, 10)
Products: (786445, 3)

,overall,vote,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime
0,2,NaN,False,2016-11-11,A2OSUEZJIN7BI,0511189877,NaN,Chris,I have an older URC-WR7 remote and thought thi...,Cannot Learn,1478822400
1,5,NaN,True,2016-06-06,A2NETQRG6JHIG7,0511189877,NaN,Qrysta White,First time I've EVER had a remote that needed ...,zero programming needed! Miracle!?,1465171200
2,4,NaN,True,2016-03-10,A12JHGROAX49G7,0511189877,NaN,Linwood,Got them and only 2 of them worked. company ca...,Works Good and programs easy.,1457568000
3,5,NaN,True,2016-01-14,A1KV65E2TMMG6F,0511189877,NaN,Dane Williams,I got tired of the remote being on the wrong s...,Same as TWC remote,1452729600
4,5,NaN,True,2016-10-20,A280POPEWI0NSA,0594459451,NaN,Kristina H.,After purchasing cheap cords from another webs...,Good Quality Cord,1476921600

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 838944 entries, 0 to 838943
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   overall         838944 non-null  int64
 1   vote            191468 non-null  object
 2   verified        838944 non-null  bool
 3   reviewTime      838944 non-null  object
 4   reviewerID      838944 non-null  object
 5   asin            838944 non-null  object
 6   style           490613 non-null  object
 7   reviewerName    838717 non-null  object
 8   reviewText      838944 non-null  object
 9   summary         838868 non-null  object
 10  unixReviewTime  838944 non-null  int64
dtypes: bool(1), int64(2), object(8)
memory usage: 64.8+ MB

In [ ]:
train_df.isnull().sum()

overall                0
vote              647476
verified               0
reviewTime             0
reviewerID             0
asin                   0
style             348331
reviewerName         227
reviewText             0
summary               76
unixReviewTime         0
dtype: int64

<div dir="rtl">
    <h2>سوال 5 </h2>
    <div>کدام محصولات بیشترین امتیاز ۵ را کسب کرده‌اند؟ ۱۰ مورد برتر را به‌ترتیب به‌صورت یک جدول شامل نام برند، عنوان محصول و تعداد نظرات با امتیاز ۵ نمایش دهید.</div>
</div>

In [ ]:
five_star = train_df[train_df["overall"] == 5]
five_star

,overall,vote,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime
1,5,NaN,True,2016-06-06,A2NETQRG6JHIG7,0511189877,NaN,Qrysta White,First time I've EVER had a remote that needed ...,zero programming needed! Miracle!?,1465171200
3,5,NaN,True,2016-01-14,A1KV65E2TMMG6F,0511189877,NaN,Dane Williams,I got tired of the remote being on the wrong s...,Same as TWC remote,1452729600
4,5,NaN,True,2016-10-20,A280POPEWI0NSA,0594459451,NaN,Kristina H.,After purchasing cheap cords from another webs...,Good Quality Cord,1476921600
5,5,NaN,True,2016-06-18,A2KTAT1Y3VRVSJ,0594459451,NaN,MnMMom3,This is a great charging cable for the Nook. ...,Better than original charger!,1466208000
6,5,NaN,True,2016-02-11,A1CHTT6E3NV5YL,0594459451,NaN,Amazon Shopper,The 90 degree connector is a bonus that allows...,Works great on my Wife's older model Nook Color.,1455148800
...,...,...,...,...,...,...,...,...,...,...,...
838935,5,NaN,True,2017-07-13,A1OOVLE2KZ6KGA,B01HJCN5GC,NaN,Puddzee,These are very nice cables. I like the heavy w...,Nice,1499904000
838938,5,NaN,True,2018-06-07,AFAI8GK0O6ZZG,B01HJDR9DQ,{'Color:': ' 1PCS BT17333 Battery'},JJC3,Fits the old cordless phones just fine and wor...,Fits and works. No issues.,1528329600
838939,5,NaN,True,2017-07-25,A1OOVLE2KZ6KGA,B01HJCN1EI,NaN,Puddzee,These are my favorite charging cords for a few...,Worth the price.,1500940800
838942,5,2.0,True,2016-12-01,A2HUZO7MQAY5I2,B01HJH40WU,NaN,michael clontz,"Ok here is an odd thing that happened to me, I...",Not the correct product as linked in the sale.,1480550400
838943,5,NaN,True,2017-03-31,A1FGCIRPRNZWD5,B01HJF704M,NaN,Brando,I have it plugged into a usb extension on my g...,Works well enough..,1490918400

In [ ]:
top_products = five_star.groupby("asin").size().reset_index(name="five_star_count")
top_products = top_products.merge(product_df[["asin", "brand", "title"]], on="asin", how="left")
top_10 = top_products.sort_values("five_star_count", ascending=False).head(10)
top_10 = top_10[["brand", "title", "five_star_count"]].reset_index(drop=True)
top_10.index += 1

top_10

,brand,title,five_star_count
1,Cambridge Soundworks,OontZ Angle 3 Enhanced Stereo Edition IPX5 Spl...,1163
2,NETGEAR,NETGEAR N300 WiFi Range Extender (EX2700),659
3,Roku,Roku Streaming Stick (3600R) - HD Streaming Pl...,600
4,StarTech,StarTech USB 2.0 to SATA IDE Adapter (USB2SATA...,598
5,Logitech,Logitech M570 Wireless Trackball Mouse &ndash;...,552
6,Samsung,Samsung 850 EVO 500GB 2.5-Inch SATA III Intern...,529
7,Asus,ASUS Tri-Band Gigabit (AC3200) WiFi Router (Up...,471
8,VideoSecu,VideoSecu ML531BE TV Wall Mount for Most 27&qu...,448
9,"Arlo Technologies, Inc",Arlo - Wireless Home Security Camera System | ...,433
10,Samsung,Samsung 850 EVO 250GB 2.5-Inch SATA III Intern...,431